-- CreateTable
CREATE TABLE `ACADEMICO_DISTINCION` (
    `ID_PERSONA` BIGINT NULL,
    `DISTINCION` VARCHAR(20) NULL,

    UNIQUE INDEX `DISTINCION`(`DISTINCION`),
    INDEX `ID_PERSONA`(`ID_PERSONA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ARTICULO` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `REVISTA` VARCHAR(50) NULL,
    `PAGINAS` FLOAT NULL,
    `EDITORIAL` VARCHAR(50) NULL,
    `INDIZACION` VARCHAR(50) NULL,
    `DOI` VARCHAR(20) NULL,
    `VOLUMEN` FLOAT NULL,
    `ISSN` VARCHAR(20) NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CAPITULO_LIBRO` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `TITULO_LIBRO` VARCHAR(256) NULL,
    `ISBN` VARCHAR(256) NULL,
    `PAGINAS` DOUBLE NULL,
    `EDITORIAL` VARCHAR(20) NULL,
    `VOLUMEN` FLOAT NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COLABORA` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `ID_PERSONA` BIGINT NOT NULL,
    `ROL` VARCHAR(20) NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    INDEX `ID_PRODUCTO`(`ID_PRODUCTO`),
    PRIMARY KEY (`ID_PERSONA`, `ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CONVENIO_MOVILIDAD` (
    `ID_CONVENIO` BIGINT NOT NULL AUTO_INCREMENT,
    `NOMBRE_INSTITUCION` VARCHAR(50) NULL,
    `SECTOR` VARCHAR(20) NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_PROGRAMA` BIGINT NULL,

    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`),
    PRIMARY KEY (`ID_CONVENIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DESIGNA` (
    `ROL` VARCHAR(20) NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_PERSONA_ACADEMICO` BIGINT NULL,
    `ID_PERSONA_ESTUDIANTE` BIGINT NULL,

    INDEX `ID_PERSONA_ACADEMICO`(`ID_PERSONA_ACADEMICO`),
    INDEX `ID_PERSONA_ESTUDIANTE`(`ID_PERSONA_ESTUDIANTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EJERCICIO_PROFESIONAL` (
    `ID_EJERCICIO_PROFESIONAL` BIGINT NOT NULL AUTO_INCREMENT,
    `INSTITUCION` VARCHAR(50) NULL,
    `TIPO` VARCHAR(20) NULL,
    `NOMBRE` VARCHAR(20) NULL,
    `DESCRIPCION` VARCHAR(256) NULL,
    `CIUDAD` VARCHAR(20) NULL,
    `ESTADO` VARCHAR(20) NULL,
    `PAIS` VARCHAR(20) NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_EJERCICIO_PROFESIONAL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EMPLEO` (
    `ID_EMPLEO` BIGINT NOT NULL AUTO_INCREMENT,
    `DESCRIPCION` VARCHAR(256) NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ARCHIVO_EVIDENCIA` BLOB NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_EMPLEO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ESTANCIA` (
    `ID_ESTANCIA` BIGINT NOT NULL AUTO_INCREMENT,
    `AMBITO` VARCHAR(20) NULL,
    `TIPO` VARCHAR(20) NULL,
    `SECTOR` VARCHAR(20) NULL,
    `PROGRAMA_DESTINO` VARCHAR(50) NULL,
    `INSTITUCION_DESTINO` VARCHAR(20) NULL,
    `MOTIVO` VARCHAR(256) NULL,
    `PAIS` VARCHAR(20) NULL,
    `ECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_CONVENIO` BIGINT NULL,
    `ID_PROGRAMA` BIGINT NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_CONVENIO`(`ID_CONVENIO`),
    INDEX `ID_PERSONA`(`ID_PERSONA`),
    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`),
    PRIMARY KEY (`ID_ESTANCIA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EVENTO` (
    `ID_EVENTO` BIGINT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(50) NULL,
    `DESCRIPCION` VARCHAR(50) NULL,
    `ARCHIVO_EVIDENCIA` BLOB NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_PROGRAMA` BIGINT NULL,

    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`),
    PRIMARY KEY (`ID_EVENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FINANCIAMIENTO` (
    `ID_FINANCIAMIENTO` BIGINT NOT NULL AUTO_INCREMENT,
    `NUMERO_BECA` BIGINT NULL,
    `DESCRIPCION` VARCHAR(256) NULL,
    `MONTO` DOUBLE NULL,
    `TIPO` VARCHAR(20) NULL,
    `OTORGANTE` VARCHAR(20) NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_FINANCIAMIENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FORMACION_COMPLEMENTARIA` (
    `ID_FORMACION_COMPLEMENTARIA` BIGINT NOT NULL AUTO_INCREMENT,
    `DESCRIPCION` VARCHAR(256) NULL,
    `TIPO` VARCHAR(20) NULL,
    `INSTITUCION` VARCHAR(50) NULL,
    `NOMBRE` VARCHAR(20) NULL,
    `ARCHIVO_EVIDENCIA` BLOB NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_FORMACION_COMPLEMENTARIA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `GENERACION` (
    `ID_GENERACION` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_PLAN` BIGINT NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,

    INDEX `ID_PLAN`(`ID_PLAN`),
    PRIMARY KEY (`ID_GENERACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `GRADO` (
    `ID_GRADO` BIGINT NOT NULL AUTO_INCREMENT,
    `NIVEL` VARCHAR(20) NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `INSTITUCION` VARCHAR(50) NULL,
    `NOMBRE_PROGRAMA` VARCHAR(50) NULL,
    `CIUDAD` VARCHAR(20) NULL,
    `ESTADO` VARCHAR(20) NULL,
    `PAIS` VARCHAR(20) NULL,
    `ARCHIVO_EVIDENCIA` BLOB NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_GRADO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LGAC` (
    `ID_LGAC` BIGINT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(256) NULL,
    `INSTITUCION` VARCHAR(50) NULL,
    `DESCRIPCION` VARCHAR(256) NULL,
    `JUSTIFICACION` TEXT NULL,
    `CLASIFICACION` VARCHAR(100) NULL,
    `ESTADO` VARCHAR(20) NULL,

    PRIMARY KEY (`ID_LGAC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LIBRO` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `ISBN` VARCHAR(15) NULL,
    `PAGINAS` DOUBLE NULL,
    `EDITORIAL` VARCHAR(20) NULL,
    `INDIZACION` VARCHAR(20) NULL,
    `VOLUMEN` FLOAT NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MEMORIA_CONGRESO` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `FECHA` DATE NULL,
    `PAGINAS` FLOAT NULL,
    `ISBN` VARCHAR(20) NULL,
    `NOMBRE_CONGRESO` VARCHAR(256) NULL,
    `CIUDAD` VARCHAR(50) NULL,
    `ESTADO` VARCHAR(50) NULL,
    `PAIS` VARCHAR(50) NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERSONA` (
    `ID_PERSONA` BIGINT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(20) NULL,
    `APELLIDO_PATERNO` VARCHAR(20) NULL,
    `APELLIDO_MATERNO` VARCHAR(20) NULL,
    `EMAIL` VARCHAR(20) NULL,
    `CVU` BIGINT NULL,
    `ESTADO` VARCHAR(20) NULL,
    `ID_GENERACION` BIGINT NULL,
    `CATEGORIA` VARCHAR(20) NULL,
    `INSTITUCION` VARCHAR(50) NULL,
    `TIPO` VARCHAR(20) NULL,

    INDEX `ID_GENERACION`(`ID_GENERACION`),
    PRIMARY KEY (`ID_PERSONA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERTENECE` (
    `ID_PROGRAMA` BIGINT NULL,
    `ID_PERSONA` BIGINT NULL,
    `FECHA_INGRESO` DATE NULL,
    `FECHA_EGRESO` DATE NULL,
    `NAB` BOOLEAN NULL,
    `CARTA_NAB` BLOB NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PLAN_ESTUDIOS` (
    `ID_PLAN` BIGINT NOT NULL AUTO_INCREMENT,
    `DESCRIPCION_MODIFICACIONES` TEXT NULL,
    `PERFIL_INGRESO` TEXT NULL,
    `PERFIL_EGRESO` TEXT NULL,
    `FECHA_INICIO` DATE NULL,
    `FECHA_FINAL` DATE NULL,
    `ID_PROGRAMA` BIGINT NULL,

    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`),
    PRIMARY KEY (`ID_PLAN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PLAN_ESTUDIOS_META` (
    `ID_PLAN` BIGINT NULL,
    `META` VARCHAR(50) NULL,

    INDEX `ID_PLAN`(`ID_PLAN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCTO_ACADEMICO` (
    `ID_PRODUCTO` BIGINT NOT NULL AUTO_INCREMENT,
    `TITULO` VARCHAR(256) NULL,
    `FECHA` DATE NULL,
    `DESCRIPCION` TEXT NULL,
    `ARCHIVO_EVIDENCIA` LONGBLOB NULL,
    `ID_LGAC` BIGINT NULL,
    `ID_ESTANCIA` BIGINT NULL,

    INDEX `ID_ESTANCIA`(`ID_ESTANCIA`),
    INDEX `ID_LGAC`(`ID_LGAC`),
    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA_EDUCATIVO` (
    `ID_PROGRAMA` BIGINT NOT NULL AUTO_INCREMENT,
    `FECHA_INICIO` DATE NULL,
    `FECHA_CREACION` DATE NULL,
    `NUMERO_ACTA` VARCHAR(20) NULL,
    `ORIENTACION` VARCHAR(20) NULL,
    `NOMBRE` VARCHAR(50) NULL,
    `GRADO` VARCHAR(20) NULL,
    `COORDINADOR` BIGINT NULL,
    `APROBADO_POR` VARCHAR(255) NULL,
    `MEDIANTE_EL` VARCHAR(255) NULL,
    `FOLIO_REGISTRO` VARCHAR(20) NULL,
    `NUMERO_RENIECYT` VARCHAR(20) NULL,
    `MODALIDAD` VARCHAR(50) NULL,
    `CARACTERISTICAS` VARCHAR(50) NULL,
    `URL` VARCHAR(200) NULL,
    `CVU` VARCHAR(20) NULL,
    `REPRESENTANTE` BIGINT NULL,
    `COORDINADOR_ACTUAL` BIGINT NULL,
    `FECHA_FIRMA` DATE NULL,

    INDEX `COORDINADOR_ACTUAL`(`COORDINADOR_ACTUAL`),
    INDEX `REPRESENTANTE`(`REPRESENTANTE`),
    INDEX `fk_coordinador`(`COORDINADOR`),
    PRIMARY KEY (`ID_PROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA_EDUCATIVO_CAMPO_CONOCIMIENTO` (
    `ID_PROGRAMA` BIGINT NULL,
    `CAMPO_CONOCIMIENTO` VARCHAR(50) NULL,

    UNIQUE INDEX `CAMPO_CONOCIMIENTO`(`CAMPO_CONOCIMIENTO`),
    INDEX `ID_PROGRAMA`(`ID_PROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROTOTIPO` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `TIPO` VARCHAR(50) NULL,
    `REGISTRO_INDAUTOR` VARCHAR(256) NULL,
    `CIUDAD` VARCHAR(20) NULL,
    `ESTADO` VARCHAR(20) NULL,
    `PAIS` VARCHAR(20) NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RECONOCIMIENTO` (
    `ID_RECONOCIMIENTO` BIGINT NOT NULL AUTO_INCREMENT,
    `ANIO` INTEGER NULL,
    `NOMBRE_PREMIO` VARCHAR(50) NULL,
    `INSTITUCION` VARCHAR(50) NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_PERSONA`(`ID_PERSONA`),
    PRIMARY KEY (`ID_RECONOCIMIENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REGISTRA` (
    `ID_LGAC` BIGINT NULL,
    `ID_PERSONA` BIGINT NULL,

    INDEX `ID_LGAC`(`ID_LGAC`),
    INDEX `ID_PERSONA`(`ID_PERSONA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SINODAL` (
    `ID_SINODAL` BIGINT NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(100) NULL,
    `CENTRO_ESTUDIOS` VARCHAR(100) NULL,
    `PROGRAMA_ESTUDIOS` VARCHAR(100) NULL,
    `EXTERNO` BOOLEAN NULL,
    `ID_PRODUCTO` BIGINT NULL,

    INDEX `ID_PRODUCTO`(`ID_PRODUCTO`),
    PRIMARY KEY (`ID_SINODAL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRABAJO_RECEPCIONAL` (
    `ID_PRODUCTO` BIGINT NOT NULL,
    `REPOSITORIO` VARCHAR(256) NULL,
    `ESTADO` VARCHAR(20) NULL,
    `ACTA` VARCHAR(20) NULL,
    `LUGAR` VARCHAR(256) NULL,
    `RESULTADO` DOUBLE NULL,

    PRIMARY KEY (`ID_PRODUCTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ACADEMICO_DISTINCION` ADD CONSTRAINT `academico_distincion_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ARTICULO` ADD CONSTRAINT `articulo_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `CAPITULO_LIBRO` ADD CONSTRAINT `capitulo_libro_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `COLABORA` ADD CONSTRAINT `colabora_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `COLABORA` ADD CONSTRAINT `colabora_ibfk_2` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `CONVENIO_MOVILIDAD` ADD CONSTRAINT `convenio_movilidad_ibfk_1` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `DESIGNA` ADD CONSTRAINT `designa_ibfk_1` FOREIGN KEY (`ID_PERSONA_ACADEMICO`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `DESIGNA` ADD CONSTRAINT `designa_ibfk_2` FOREIGN KEY (`ID_PERSONA_ESTUDIANTE`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `EJERCICIO_PROFESIONAL` ADD CONSTRAINT `ejercicio_profesional_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `EMPLEO` ADD CONSTRAINT `empleo_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ESTANCIA` ADD CONSTRAINT `estancia_ibfk_1` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ESTANCIA` ADD CONSTRAINT `estancia_ibfk_2` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ESTANCIA` ADD CONSTRAINT `estancia_ibfk_3` FOREIGN KEY (`ID_CONVENIO`) REFERENCES `CONVENIO_MOVILIDAD`(`ID_CONVENIO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `EVENTO` ADD CONSTRAINT `evento_ibfk_1` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `FINANCIAMIENTO` ADD CONSTRAINT `financiamiento_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `FORMACION_COMPLEMENTARIA` ADD CONSTRAINT `formacion_complementaria_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `GENERACION` ADD CONSTRAINT `generacion_ibfk_1` FOREIGN KEY (`ID_PLAN`) REFERENCES `PLAN_ESTUDIOS`(`ID_PLAN`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `GRADO` ADD CONSTRAINT `grado_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `LIBRO` ADD CONSTRAINT `libro_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `MEMORIA_CONGRESO` ADD CONSTRAINT `memoria_congreso_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PERSONA` ADD CONSTRAINT `persona_ibfk_1` FOREIGN KEY (`ID_GENERACION`) REFERENCES `GENERACION`(`ID_GENERACION`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PERTENECE` ADD CONSTRAINT `pertenece_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PERTENECE` ADD CONSTRAINT `pertenece_ibfk_2` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PLAN_ESTUDIOS` ADD CONSTRAINT `plan_estudios_ibfk_1` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PLAN_ESTUDIOS_META` ADD CONSTRAINT `plan_estudios_meta_ibfk_1` FOREIGN KEY (`ID_PLAN`) REFERENCES `PLAN_ESTUDIOS`(`ID_PLAN`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PRODUCTO_ACADEMICO` ADD CONSTRAINT `producto_academico_ibfk_1` FOREIGN KEY (`ID_LGAC`) REFERENCES `LGAC`(`ID_LGAC`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PRODUCTO_ACADEMICO` ADD CONSTRAINT `producto_academico_ibfk_2` FOREIGN KEY (`ID_ESTANCIA`) REFERENCES `ESTANCIA`(`ID_ESTANCIA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PROGRAMA_EDUCATIVO` ADD CONSTRAINT `fk_coordinador` FOREIGN KEY (`COORDINADOR`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PROGRAMA_EDUCATIVO` ADD CONSTRAINT `programa_educativo_ibfk_1` FOREIGN KEY (`COORDINADOR_ACTUAL`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA_EDUCATIVO` ADD CONSTRAINT `programa_educativo_ibfk_2` FOREIGN KEY (`REPRESENTANTE`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA_EDUCATIVO_CAMPO_CONOCIMIENTO` ADD CONSTRAINT `programa_educativo_campo_conocimiento_ibfk_1` FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMA_EDUCATIVO`(`ID_PROGRAMA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `PROTOTIPO` ADD CONSTRAINT `prototipo_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `RECONOCIMIENTO` ADD CONSTRAINT `reconocimiento_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `REGISTRA` ADD CONSTRAINT `registra_ibfk_1` FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA`(`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `REGISTRA` ADD CONSTRAINT `registra_ibfk_2` FOREIGN KEY (`ID_LGAC`) REFERENCES `LGAC`(`ID_LGAC`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `SINODAL` ADD CONSTRAINT `sinodal_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `TRABAJO_RECEPCIONAL`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TRABAJO_RECEPCIONAL` ADD CONSTRAINT `trabajo_recepcional_ibfk_1` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO_ACADEMICO`(`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
